/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChecklistsRouteImport } from './routes/_authenticated/checklists'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedMeusConteudosRouteImport } from './routes/_authenticated/meus-conteudos'
import { Route as AuthenticatedPersonagensRouteImport } from './routes/_authenticated/personagens'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedChecklistsAcompanhamentoRouteImport } from './routes/_authenticated/checklists.acompanhamento'
import { Route as AuthenticatedChecklistsLiberacoesRouteImport } from './routes/_authenticated/checklists.liberacoes'
import { Route as AuthenticatedChecklistsSetoresRouteImport } from './routes/_authenticated/checklists.setores'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores.index'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'
import { Route as AuthenticatedMeusConteudosIndexRouteImport } from './routes/_authenticated/meus-conteudos.index'
import { Route as AuthenticatedPersonagensIndexRouteImport } from './routes/_authenticated/personagens.index'
import { Route as AuthenticatedPersonagensBibliotecaRouteImport } from './routes/_authenticated/personagens.biblioteca'
import { Route as AuthenticatedPersonagensImprimirRouteImport } from './routes/_authenticated/personagens.imprimir'
import { Route as AuthenticatedPersonagensSimulacaoRouteImport } from './routes/_authenticated/personagens.simulacao'
import { Route as AuthenticatedChecklistsAvaliacoesIndexRouteImport } from './routes/_authenticated/checklists.avaliacoes.index'
import { Route as AuthenticatedChecklistsAvaliacoesIdRouteImport } from './routes/_authenticated/checklists.avaliacoes.$id'
import { Route as AuthenticatedChecklistsModelosIndexRouteImport } from './routes/_authenticated/checklists.modelos.index'
import { Route as AuthenticatedChecklistsModelosIdRouteImport } from './routes/_authenticated/checklists.modelos.$id'
import { Route as AuthenticatedMeusConteudosSimuladoIdRouteImport } from './routes/_authenticated/meus-conteudos.simulado.$id'
import { Route as AuthenticatedPersonagensPersonasIdRouteImport } from './routes/_authenticated/personagens.personas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistsRoute = AuthenticatedChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusConteudosRoute =
  AuthenticatedMeusConteudosRouteImport.update({
    id: '/meus-conteudos',
    path: '/meus-conteudos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonagensRoute =
  AuthenticatedPersonagensRouteImport.update({
    id: '/personagens',
    path: '/personagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsAcompanhamentoRoute =
  AuthenticatedChecklistsAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsLiberacoesRoute =
  AuthenticatedChecklistsLiberacoesRouteImport.update({
    id: '/liberacoes',
    path: '/liberacoes',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsSetoresRoute =
  AuthenticatedChecklistsSetoresRouteImport.update({
    id: '/setores',
    path: '/setores',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedColaboradoresRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedColaboradoresRoute,
  } as any)
const AuthenticatedMeusConteudosIndexRoute =
  AuthenticatedMeusConteudosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeusConteudosRoute,
  } as any)
const AuthenticatedPersonagensIndexRoute =
  AuthenticatedPersonagensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPersonagensRoute,
  } as any)
const AuthenticatedPersonagensBibliotecaRoute =
  AuthenticatedPersonagensBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedPersonagensRoute,
  } as any)
const AuthenticatedPersonagensImprimirRoute =
  AuthenticatedPersonagensImprimirRouteImport.update({
    id: '/imprimir',
    path: '/imprimir',
    getParentRoute: () => AuthenticatedPersonagensRoute,
  } as any)
const AuthenticatedPersonagensSimulacaoRoute =
  AuthenticatedPersonagensSimulacaoRouteImport.update({
    id: '/simulacao',
    path: '/simulacao',
    getParentRoute: () => AuthenticatedPersonagensRoute,
  } as any)
const AuthenticatedChecklistsAvaliacoesIndexRoute =
  AuthenticatedChecklistsAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsAvaliacoesIdRoute =
  AuthenticatedChecklistsAvaliacoesIdRouteImport.update({
    id: '/avaliacoes/$id',
    path: '/avaliacoes/$id',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsModelosIndexRoute =
  AuthenticatedChecklistsModelosIndexRouteImport.update({
    id: '/modelos/',
    path: '/modelos/',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedChecklistsModelosIdRoute =
  AuthenticatedChecklistsModelosIdRouteImport.update({
    id: '/modelos/$id',
    path: '/modelos/$id',
    getParentRoute: () => AuthenticatedChecklistsRoute,
  } as any)
const AuthenticatedMeusConteudosSimuladoIdRoute =
  AuthenticatedMeusConteudosSimuladoIdRouteImport.update({
    id: '/simulado/$id',
    path: '/simulado/$id',
    getParentRoute: () => AuthenticatedMeusConteudosRoute,
  } as any)
const AuthenticatedPersonagensPersonasIdRoute =
  AuthenticatedPersonagensPersonasIdRouteImport.update({
    id: '/personas/$id',
    path: '/personas/$id',
    getParentRoute: () => AuthenticatedPersonagensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checklists': typeof AuthenticatedChecklistsRouteWithChildren
  '/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/meus-conteudos': typeof AuthenticatedMeusConteudosRouteWithChildren
  '/personagens': typeof AuthenticatedPersonagensRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/checklists/acompanhamento': typeof AuthenticatedChecklistsAcompanhamentoRoute
  '/checklists/liberacoes': typeof AuthenticatedChecklistsLiberacoesRoute
  '/checklists/setores': typeof AuthenticatedChecklistsSetoresRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/personagens/biblioteca': typeof AuthenticatedPersonagensBibliotecaRoute
  '/personagens/imprimir': typeof AuthenticatedPersonagensImprimirRoute
  '/personagens/simulacao': typeof AuthenticatedPersonagensSimulacaoRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/meus-conteudos/': typeof AuthenticatedMeusConteudosIndexRoute
  '/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/checklists/avaliacoes/$id': typeof AuthenticatedChecklistsAvaliacoesIdRoute
  '/checklists/modelos/$id': typeof AuthenticatedChecklistsModelosIdRoute
  '/meus-conteudos/simulado/$id': typeof AuthenticatedMeusConteudosSimuladoIdRoute
  '/personagens/personas/$id': typeof AuthenticatedPersonagensPersonasIdRoute
  '/checklists/avaliacoes/': typeof AuthenticatedChecklistsAvaliacoesIndexRoute
  '/checklists/modelos/': typeof AuthenticatedChecklistsModelosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/checklists/acompanhamento': typeof AuthenticatedChecklistsAcompanhamentoRoute
  '/checklists/liberacoes': typeof AuthenticatedChecklistsLiberacoesRoute
  '/checklists/setores': typeof AuthenticatedChecklistsSetoresRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/personagens/biblioteca': typeof AuthenticatedPersonagensBibliotecaRoute
  '/personagens/imprimir': typeof AuthenticatedPersonagensImprimirRoute
  '/personagens/simulacao': typeof AuthenticatedPersonagensSimulacaoRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
  '/meus-conteudos': typeof AuthenticatedMeusConteudosIndexRoute
  '/personagens': typeof AuthenticatedPersonagensIndexRoute
  '/checklists/avaliacoes/$id': typeof AuthenticatedChecklistsAvaliacoesIdRoute
  '/checklists/modelos/$id': typeof AuthenticatedChecklistsModelosIdRoute
  '/meus-conteudos/simulado/$id': typeof AuthenticatedMeusConteudosSimuladoIdRoute
  '/personagens/personas/$id': typeof AuthenticatedPersonagensPersonasIdRoute
  '/checklists/avaliacoes': typeof AuthenticatedChecklistsAvaliacoesIndexRoute
  '/checklists/modelos': typeof AuthenticatedChecklistsModelosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checklists': typeof AuthenticatedChecklistsRouteWithChildren
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/_authenticated/meus-conteudos': typeof AuthenticatedMeusConteudosRouteWithChildren
  '/_authenticated/personagens': typeof AuthenticatedPersonagensRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/checklists/acompanhamento': typeof AuthenticatedChecklistsAcompanhamentoRoute
  '/_authenticated/checklists/liberacoes': typeof AuthenticatedChecklistsLiberacoesRoute
  '/_authenticated/checklists/setores': typeof AuthenticatedChecklistsSetoresRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/personagens/biblioteca': typeof AuthenticatedPersonagensBibliotecaRoute
  '/_authenticated/personagens/imprimir': typeof AuthenticatedPersonagensImprimirRoute
  '/_authenticated/personagens/simulacao': typeof AuthenticatedPersonagensSimulacaoRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/_authenticated/meus-conteudos/': typeof AuthenticatedMeusConteudosIndexRoute
  '/_authenticated/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/_authenticated/checklists/avaliacoes/$id': typeof AuthenticatedChecklistsAvaliacoesIdRoute
  '/_authenticated/checklists/modelos/$id': typeof AuthenticatedChecklistsModelosIdRoute
  '/_authenticated/meus-conteudos/simulado/$id': typeof AuthenticatedMeusConteudosSimuladoIdRoute
  '/_authenticated/personagens/personas/$id': typeof AuthenticatedPersonagensPersonasIdRoute
  '/_authenticated/checklists/avaliacoes/': typeof AuthenticatedChecklistsAvaliacoesIndexRoute
  '/_authenticated/checklists/modelos/': typeof AuthenticatedChecklistsModelosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/checklists'
    | '/colaboradores'
    | '/meus-conteudos'
    | '/personagens'
    | '/portal'
    | '/checklists/acompanhamento'
    | '/checklists/liberacoes'
    | '/checklists/setores'
    | '/colaboradores/$id'
    | '/personagens/biblioteca'
    | '/personagens/imprimir'
    | '/personagens/simulacao'
    | '/checklists/'
    | '/colaboradores/'
    | '/meus-conteudos/'
    | '/personagens/'
    | '/checklists/avaliacoes/$id'
    | '/checklists/modelos/$id'
    | '/meus-conteudos/simulado/$id'
    | '/personagens/personas/$id'
    | '/checklists/avaliacoes/'
    | '/checklists/modelos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/portal'
    | '/checklists/acompanhamento'
    | '/checklists/liberacoes'
    | '/checklists/setores'
    | '/colaboradores/$id'
    | '/personagens/biblioteca'
    | '/personagens/imprimir'
    | '/personagens/simulacao'
    | '/checklists'
    | '/colaboradores'
    | '/meus-conteudos'
    | '/personagens'
    | '/checklists/avaliacoes/$id'
    | '/checklists/modelos/$id'
    | '/meus-conteudos/simulado/$id'
    | '/personagens/personas/$id'
    | '/checklists/avaliacoes'
    | '/checklists/modelos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/checklists'
    | '/_authenticated/colaboradores'
    | '/_authenticated/meus-conteudos'
    | '/_authenticated/personagens'
    | '/_authenticated/portal'
    | '/_authenticated/checklists/acompanhamento'
    | '/_authenticated/checklists/liberacoes'
    | '/_authenticated/checklists/setores'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/personagens/biblioteca'
    | '/_authenticated/personagens/imprimir'
    | '/_authenticated/personagens/simulacao'
    | '/_authenticated/checklists/'
    | '/_authenticated/colaboradores/'
    | '/_authenticated/meus-conteudos/'
    | '/_authenticated/personagens/'
    | '/_authenticated/checklists/avaliacoes/$id'
    | '/_authenticated/checklists/modelos/$id'
    | '/_authenticated/meus-conteudos/simulado/$id'
    | '/_authenticated/personagens/personas/$id'
    | '/_authenticated/checklists/avaliacoes/'
    | '/_authenticated/checklists/modelos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists': {
      id: '/_authenticated/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthenticatedChecklistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-conteudos': {
      id: '/_authenticated/meus-conteudos'
      path: '/meus-conteudos'
      fullPath: '/meus-conteudos'
      preLoaderRoute: typeof AuthenticatedMeusConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personagens': {
      id: '/_authenticated/personagens'
      path: '/personagens'
      fullPath: '/personagens'
      preLoaderRoute: typeof AuthenticatedPersonagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/acompanhamento': {
      id: '/_authenticated/checklists/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/checklists/acompanhamento'
      preLoaderRoute: typeof AuthenticatedChecklistsAcompanhamentoRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/liberacoes': {
      id: '/_authenticated/checklists/liberacoes'
      path: '/liberacoes'
      fullPath: '/checklists/liberacoes'
      preLoaderRoute: typeof AuthenticatedChecklistsLiberacoesRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/setores': {
      id: '/_authenticated/checklists/setores'
      path: '/setores'
      fullPath: '/checklists/setores'
      preLoaderRoute: typeof AuthenticatedChecklistsSetoresRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedColaboradoresRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedColaboradoresRoute
    }
    '/_authenticated/meus-conteudos/': {
      id: '/_authenticated/meus-conteudos/'
      path: '/'
      fullPath: '/meus-conteudos/'
      preLoaderRoute: typeof AuthenticatedMeusConteudosIndexRouteImport
      parentRoute: typeof AuthenticatedMeusConteudosRoute
    }
    '/_authenticated/personagens/': {
      id: '/_authenticated/personagens/'
      path: '/'
      fullPath: '/personagens/'
      preLoaderRoute: typeof AuthenticatedPersonagensIndexRouteImport
      parentRoute: typeof AuthenticatedPersonagensRoute
    }
    '/_authenticated/personagens/biblioteca': {
      id: '/_authenticated/personagens/biblioteca'
      path: '/biblioteca'
      fullPath: '/personagens/biblioteca'
      preLoaderRoute: typeof AuthenticatedPersonagensBibliotecaRouteImport
      parentRoute: typeof AuthenticatedPersonagensRoute
    }
    '/_authenticated/personagens/imprimir': {
      id: '/_authenticated/personagens/imprimir'
      path: '/imprimir'
      fullPath: '/personagens/imprimir'
      preLoaderRoute: typeof AuthenticatedPersonagensImprimirRouteImport
      parentRoute: typeof AuthenticatedPersonagensRoute
    }
    '/_authenticated/personagens/simulacao': {
      id: '/_authenticated/personagens/simulacao'
      path: '/simulacao'
      fullPath: '/personagens/simulacao'
      preLoaderRoute: typeof AuthenticatedPersonagensSimulacaoRouteImport
      parentRoute: typeof AuthenticatedPersonagensRoute
    }
    '/_authenticated/checklists/avaliacoes/': {
      id: '/_authenticated/checklists/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/checklists/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedChecklistsAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/avaliacoes/$id': {
      id: '/_authenticated/checklists/avaliacoes/$id'
      path: '/avaliacoes/$id'
      fullPath: '/checklists/avaliacoes/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsAvaliacoesIdRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/modelos/': {
      id: '/_authenticated/checklists/modelos/'
      path: '/modelos'
      fullPath: '/checklists/modelos/'
      preLoaderRoute: typeof AuthenticatedChecklistsModelosIndexRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/checklists/modelos/$id': {
      id: '/_authenticated/checklists/modelos/$id'
      path: '/modelos/$id'
      fullPath: '/checklists/modelos/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsModelosIdRouteImport
      parentRoute: typeof AuthenticatedChecklistsRoute
    }
    '/_authenticated/meus-conteudos/simulado/$id': {
      id: '/_authenticated/meus-conteudos/simulado/$id'
      path: '/simulado/$id'
      fullPath: '/meus-conteudos/simulado/$id'
      preLoaderRoute: typeof AuthenticatedMeusConteudosSimuladoIdRouteImport
      parentRoute: typeof AuthenticatedMeusConteudosRoute
    }
    '/_authenticated/personagens/personas/$id': {
      id: '/_authenticated/personagens/personas/$id'
      path: '/personas/$id'
      fullPath: '/personagens/personas/$id'
      preLoaderRoute: typeof AuthenticatedPersonagensPersonasIdRouteImport
      parentRoute: typeof AuthenticatedPersonagensRoute
    }
  }
}

interface AuthenticatedChecklistsRouteChildren {
  AuthenticatedChecklistsAcompanhamentoRoute: typeof AuthenticatedChecklistsAcompanhamentoRoute
  AuthenticatedChecklistsLiberacoesRoute: typeof AuthenticatedChecklistsLiberacoesRoute
  AuthenticatedChecklistsSetoresRoute: typeof AuthenticatedChecklistsSetoresRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
  AuthenticatedChecklistsAvaliacoesIdRoute: typeof AuthenticatedChecklistsAvaliacoesIdRoute
  AuthenticatedChecklistsModelosIdRoute: typeof AuthenticatedChecklistsModelosIdRoute
  AuthenticatedChecklistsAvaliacoesIndexRoute: typeof AuthenticatedChecklistsAvaliacoesIndexRoute
  AuthenticatedChecklistsModelosIndexRoute: typeof AuthenticatedChecklistsModelosIndexRoute
}

const AuthenticatedChecklistsRouteChildren: AuthenticatedChecklistsRouteChildren =
  {
    AuthenticatedChecklistsAcompanhamentoRoute:
      AuthenticatedChecklistsAcompanhamentoRoute,
    AuthenticatedChecklistsLiberacoesRoute:
      AuthenticatedChecklistsLiberacoesRoute,
    AuthenticatedChecklistsSetoresRoute: AuthenticatedChecklistsSetoresRoute,
    AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
    AuthenticatedChecklistsAvaliacoesIdRoute:
      AuthenticatedChecklistsAvaliacoesIdRoute,
    AuthenticatedChecklistsModelosIdRoute:
      AuthenticatedChecklistsModelosIdRoute,
    AuthenticatedChecklistsAvaliacoesIndexRoute:
      AuthenticatedChecklistsAvaliacoesIndexRoute,
    AuthenticatedChecklistsModelosIndexRoute:
      AuthenticatedChecklistsModelosIndexRoute,
  }

const AuthenticatedChecklistsRouteWithChildren =
  AuthenticatedChecklistsRoute._addFileChildren(
    AuthenticatedChecklistsRouteChildren,
  )

interface AuthenticatedColaboradoresRouteChildren {
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
}

const AuthenticatedColaboradoresRouteChildren: AuthenticatedColaboradoresRouteChildren =
  {
    AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
    AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
  }

const AuthenticatedColaboradoresRouteWithChildren =
  AuthenticatedColaboradoresRoute._addFileChildren(
    AuthenticatedColaboradoresRouteChildren,
  )

interface AuthenticatedMeusConteudosRouteChildren {
  AuthenticatedMeusConteudosIndexRoute: typeof AuthenticatedMeusConteudosIndexRoute
  AuthenticatedMeusConteudosSimuladoIdRoute: typeof AuthenticatedMeusConteudosSimuladoIdRoute
}

const AuthenticatedMeusConteudosRouteChildren: AuthenticatedMeusConteudosRouteChildren =
  {
    AuthenticatedMeusConteudosIndexRoute: AuthenticatedMeusConteudosIndexRoute,
    AuthenticatedMeusConteudosSimuladoIdRoute:
      AuthenticatedMeusConteudosSimuladoIdRoute,
  }

const AuthenticatedMeusConteudosRouteWithChildren =
  AuthenticatedMeusConteudosRoute._addFileChildren(
    AuthenticatedMeusConteudosRouteChildren,
  )

interface AuthenticatedPersonagensRouteChildren {
  AuthenticatedPersonagensBibliotecaRoute: typeof AuthenticatedPersonagensBibliotecaRoute
  AuthenticatedPersonagensImprimirRoute: typeof AuthenticatedPersonagensImprimirRoute
  AuthenticatedPersonagensSimulacaoRoute: typeof AuthenticatedPersonagensSimulacaoRoute
  AuthenticatedPersonagensIndexRoute: typeof AuthenticatedPersonagensIndexRoute
  AuthenticatedPersonagensPersonasIdRoute: typeof AuthenticatedPersonagensPersonasIdRoute
}

const AuthenticatedPersonagensRouteChildren: AuthenticatedPersonagensRouteChildren =
  {
    AuthenticatedPersonagensBibliotecaRoute:
      AuthenticatedPersonagensBibliotecaRoute,
    AuthenticatedPersonagensImprimirRoute:
      AuthenticatedPersonagensImprimirRoute,
    AuthenticatedPersonagensSimulacaoRoute:
      AuthenticatedPersonagensSimulacaoRoute,
    AuthenticatedPersonagensIndexRoute: AuthenticatedPersonagensIndexRoute,
    AuthenticatedPersonagensPersonasIdRoute:
      AuthenticatedPersonagensPersonasIdRoute,
  }

const AuthenticatedPersonagensRouteWithChildren =
  AuthenticatedPersonagensRoute._addFileChildren(
    AuthenticatedPersonagensRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChecklistsRoute: typeof AuthenticatedChecklistsRouteWithChildren
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRouteWithChildren
  AuthenticatedMeusConteudosRoute: typeof AuthenticatedMeusConteudosRouteWithChildren
  AuthenticatedPersonagensRoute: typeof AuthenticatedPersonagensRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChecklistsRoute: AuthenticatedChecklistsRouteWithChildren,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRouteWithChildren,
  AuthenticatedMeusConteudosRoute: AuthenticatedMeusConteudosRouteWithChildren,
  AuthenticatedPersonagensRoute: AuthenticatedPersonagensRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
